### ISSUE TITLE
chore: fix PR template

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#26]
1. Markdown hierarchy 문제
  알 수 없는 이유로 모든 제목이 H2 로 시작합니다.

2. 타인 Assignee 지정
  체크리스트에 자신이 아닌 타인을 assignee 로 지정하게 되어있습니다. 지난번 회의 때 들었던 협업 방식과 내용이 다른데, 어떤 것이 맞는지 알려주세요.

3. 불필요한 HTML tag
  Markdown 에 필요없는 HTML tag 가 포함되어있습니다.

**Comment by ghd64845** [comment]
개선 해주셔서 감사합니다!

**Comment by kimseungbin** [comment]
> 개선 해주셔서 감사합니다!

앗 제가 담당해서 할까요? (아직 깃헙 아이디가 익숙치 않아) 원래 작성자분이 누구신지 몰라서 이슈를 열어둔 것이었습니다.

**Comment by kimseungbin** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users
