### ISSUE TITLE
infra(GitHub): implement Code Owners

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#29]
# Description

- CodeOwners 를 지정해 디렉토리 별 리뷰어 자동 지정

# Reference

[About Code Owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

# Todos

- [x] CODEOWNERS 추가
- [x] 추가적으로 전체 인원 대상 Team 을 생성해서 여려멍을 수동으로 reviewers 로 지정하는 작업 삭제

**Comment by Ooyd** [comment]
CODEOWNERS는 역할이 남는 부분은 임시로 제가 가져갔습니다.
또한 Manage access에 팀원 4명 생성했습니다.
