### ISSUE TITLE
infra(GitHub): Rule sets

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#34]
# Description

- Repository 에 Rule set 이 존재하지 않아 안전장치 없이 병합이 되는 것을 확인했습니다.
  이에 Rule set 추가를 건의드립니다.

**Comment by junman95** [comment]
어떠한 룰이 보편적으로 필요한가요??

**Comment by kimseungbin** [comment]
일단 현재의 문제는

1. 2023년 부로 branch protection rule -> rulesets 로 바뀐 부분이 반영되지 않은 점
2. stale approval 이 남는다는 점
3. Code Owners 에 대한 검사를 하지 않는다는 점
4. Status check 가 실패해도 병합이 되는 점
5. 대화가 해결되지 않은 상태에서도 병합이 가능한 점
6. **linear history 를 강제하지 않는 점** (현재 코드 리뷰 시 가독성을 많이 떨어뜨립니다.)

다음은 우려사항입니다.
1. 팀 규모에 비해 적은 최소 승인 수
2. gpg sign commit 을 허용하는 점

**Comment by kimseungbin** [comment]
차주부터 적용하는 것으로 논의됨
