### ISSUE TITLE
docs: 로깅 사전 학습

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#49]
# Description

- 각자 조사한 자료를 정리해서 댓글에 달기
- 담당자가 정리해서 PR 올리기

# Todos

- [x] #50
- [x] #51
- [x] #52

**Comment by junman95** [comment]
Due date - 23.10.16

**Comment by Ooyd** [comment]
사전 학습하면서 따로 정리한부분 우선공유합니다
각 이슈에 대해 Reference들만 따로 다시 올릴게요!
[**전체정리**](https://daily-sherbet-859.notion.site/Logging-37532bfaad8b4ac591a3abc62d882fdc?pvs=4)
