### ISSUE TITLE
docs: Logging 사전 학습

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#50]
# Description

- 로깅에 대한 전반적인 사전 학습 댓글 모음
- 로깅 이유, 방법, 포맷 등을 논의

**Comment by Ooyd** [comment]
[**로깅이 왜중요한가?-Medium**](https://apoorv-tomar.medium.com/logging-why-logging-is-important-9ef989867a08)
-> 슥 찾아보다가 간단하게 읽기 좋을거같아서 공유합니다.
