### ISSUE TITLE
docs: CloudWatch 사전 학습

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#52]
# Description

- AWS CloudWatch 사전 학습 관련 내용 댓글 모음

**Comment by kimseungbin** [comment]
[공식 문서](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html)

**Comment by Ooyd** [comment]
[**AWS CloudWatch logging에 대한 실시간알림**](https://medium.com/insiderengineering/realtime-alerting-from-applications-logs-in-amazon-cloudwatch-168b2cb587fd)
[**Introduce AWS CloudWatch**](https://aws.plainenglish.io/aws-cloudwatch-introduction-9750af3d91f9)
