### ISSUE TITLE
feat: install and configure Winston

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#58]
# Description

# Todos

- [x] 필요한 dependencies 설치
- [ ] AWS CloudWatch 와 사용할 수 있도록 설정

**Comment by Ooyd** [comment]
[CloudWatch Options](https://www.npmjs.com/package/winston-cloudwatch#options)

**Comment by kimseungbin** [comment]
생각해보니 ECS 에서 굳이 winston-cloudwatch 같은 sdk 에 의존하는 도구를 써야하나 의문입니다.
그냥 ECS 로그스트림을 CW 로 잡으면 콘솔에 찍어도 자동으로 가져서...

**Comment by Ooyd** [comment]
AWS 내의 서비스끼리니 그렇네요. 말씀대로라면 해당 도구의 사용이유는 조금 사라질수있을거같습니다.
그래도 해당도구 사용으로 로깅커스텀이나 추가적 제어도 가능하니 우선은 적용시켜보고 작업하는것도 좋을거같습니다.

**Comment by kimseungbin** [comment]
> AWS 내의 서비스끼리니 그렇네요. 말씀대로라면 해당 도구의 사용이유는 조금 사라질수있을거같습니다. 그래도 해당도구 사용으로 로깅커스텀이나 추가적 제어도 가능하니 우선은 적용시켜보고 작업하는것도 좋을거같습니다.

맞습니다! 사용하는 걸 항해에서 권장했으니깐요. 다만 제가 걱정인건 오늘이 제출날이라서...

**Comment by Ooyd** [comment]
승빈님 걱정대로 힘든 상황이 온다면, AWS내에서 작업을 하는방향도 고려해도 좋을거같습니다.
중요하다 생각되는게 사실 로깅을 통한 모니터링이어서 그 부분에 중점을 두는것도 좋을거 같습니다.
